#pragma once

#include <cinder/app/App.h>
#include <cinder/app/RendererGl.h>
#include <cinder/gl/gl.h>
#include <cinder/Camera.h>
#include <cinder/params/Params.h>
#include <cinder/Arcball.h>
#include <cinder/Area.h>
#include <cinder/AxisAlignedBox.h>
#include <cinder/BandedMatrix.h>
#include <cinder/Base64.h>
#include <cinder/Breakpoint.h>
#include <cinder/BSpline.h>
#include <cinder/BSplineFit.h>
#include <cinder/Buffer.h>
#include <cinder/Camera.h>
#include <cinder/CameraUi.h>
#include <cinder/Channel.h>
#include <cinder/Cinder.h>
#include <cinder/CinderGlm.h>
#include <cinder/CinderImGui.h>
#include <cinder/CinderImGuiConfig.h>
#include <cinder/CinderMath.h>
#include <cinder/CinderResources.h>
#include <cinder/Clipboard.h>
#include <cinder/Color.h>
#include <cinder/ConcurrentCircularBuffer.h>
#include <cinder/CurrentFunction.h>
#include <cinder/DataSource.h>
#include <cinder/DataTarget.h>
#include <cinder/Display.h>
#include <cinder/Easing.h>
#include <cinder/Exception.h>
#include <cinder/Export.h>
#include <cinder/Filesystem.h>
#include <cinder/FileWatcher.h>
#include <cinder/Filter.h>
#include <cinder/Font.h>
#include <cinder/Function.h>
#include <cinder/ImageIo.h>
#include <cinder/Json.h>
#include <cinder/KdTree.h>
#include <cinder/Log.h>
#include <cinder/Matrix.h>
#include <cinder/Matrix22.h>
#include <cinder/Matrix33.h>
#include <cinder/Matrix44.h>
#include <cinder/MediaTime.h>
#include <cinder/Noncopyable.h>
#include <cinder/ObjLoader.h>
#include <cinder/Path2d.h>
#include <cinder/Perlin.h>
#include <cinder/Plane.h>
#include <cinder/PolyLine.h>
#include <cinder/Quaternion.h>
#include <cinder/Rand.h>
#include <cinder/Ray.h>
#include <cinder/Rect.h>
#include <cinder/Serial.h>
#include <cinder/Shape2d.h>
#include <cinder/Signals.h>
#include <cinder/Sphere.h>
#include <cinder/Surface.h>
#include <cinder/Text.h>
#include <cinder/Thread.h>
#include <cinder/Timeline.h>
#include <cinder/TimelineItem.h>
#include <cinder/Timer.h>
#include <cinder/Triangulate.h>
#include <cinder/TriMesh.h>
#include <cinder/Tween.h>
#include <cinder/Unicode.h>
#include <cinder/Utilities.h>
#include <cinder/Vector.h>
#include <cinder/Xml.h>
#include <cinder/ip/Blend.h>
#include <cinder/ip/Blur.h>
#include <cinder/ip/Checkerboard.h>
#include <cinder/ip/EdgeDetect.h>
#include <cinder/ip/Fill.h>
#include <cinder/ip/FLip.h>
#include <cinder/ip/Greyscale.h>
#include <cinder/ip/Hdr.h>
#include <cinder/ip/Premultiply.h>
#include <cinder/ip/Resize.h>
#include <cinder/ip/Threshold.h>
#include <cinder/ip/Trim.h>
